### ISSUE TITLE
Ubuntu18.04无法编译

### ISSUE THREAD

**Issue by hootigger** [haishanh/yacd#547]
下面是部分环境

```Bash
xxx@ubuntu-server:/opt/src$ uname -a
Linux ubuntu-server 4.19.0-6.ucloud #1 SMP Wed Feb 12 08:20:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
xxx@ubuntu-server:/opt/src$ docker -v
Docker version 19.03.6, build 369ce74a3c
```
编译的日志.使用docker

```Bash
Building yacd
Step 1/8 : FROM node:alpine AS builder
 ---> 1e55b2e48c8e
Step 2/8 : WORKDIR /app
 ---> Using cache
 ---> 2224656cbe7a
Step 3/8 : COPY tmp/yacd .
 ---> Using cache
 ---> bde90aac8b4e
Step 4/8 : RUN yarn config set network-timeout 300000   && yarn   && yarn build   && rm public/*.map
 ---> Running in 786d159ab686
yarn config v1.22.5
success Set "network-timeout" to "300000".
Done in 0.04s.
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @hsjs/react-cache@0.0.0-alpha.aa94237" has incorrect peer dependency "react@^16.3.0-alpha.1".
warning " > @reach/tooltip@0.11.2" has incorrect peer dependency "react@^16.8.0".
warning " > @reach/tooltip@0.11.2" has incorrect peer dependency "react-dom@^16.8.0".
warning "@reach/tooltip > @reach/auto-id@0.11.2" has incorrect peer dependency "react@^16.8.0".
warning "@reach/tooltip > @reach/auto-id@0.11.2" has incorrect peer dependency "react-dom@^16.8.0".
warning "@reach/tooltip > @reach/portal@0.11.2" has incorrect peer dependency "react@^16.8.0".
warning "@reach/tooltip > @reach/portal@0.11.2" has incorrect peer dependency "react-dom@^16.8.0".
warning "@reach/tooltip > @reach/rect@0.11.2" has incorrect peer dependency "react@^16.8.0".
warning "@reach/tooltip > @reach/rect@0.11.2" has incorrect peer dependency "react-dom@^16.8.0".
warning "@reach/tooltip > @reach/utils@0.11.2" has incorrect peer dependency "react@^16.8.0".
warning "@reach/tooltip > @reach/utils@0.11.2" has incorrect peer dependency "react-dom@^16.8.0".
warning "@reach/tooltip > @reach/visually-hidden@0.11.1" has incorrect peer dependency "react@^16.8.0".
warning "@reach/tooltip > @reach/visually-hidden@0.11.1" has incorrect peer dependency "react-dom@^16.8.0".
warning " > framer-motion@2.9.4" has incorrect peer dependency "react@^16.8".
warning " > framer-motion@2.9.4" has incorrect peer dependency "react-dom@^16.8".
warning " > react-feather@2.0.9" has incorrect peer dependency "react@^16.8.6 || ^17".
warning " > react-helmet@6.1.0" has incorrect peer dependency "react@>=16.3.0".
warning "react-helmet > react-side-effect@2.1.0" has incorrect peer dependency "react@^16.3.0".
warning " > react-modal@3.11.2" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16".
warning " > react-modal@3.11.2" has incorrect peer dependency "react-dom@^0.14.0 || ^15.0.0 || ^16".
warning " > react-query@2.26.3" has incorrect peer dependency "react@^16.8.0 || ^17.0.0".
warning " > react-router@6.0.0-beta.0" has incorrect peer dependency "react@>=16.8".
warning " > react-router-dom@6.0.0-beta.0" has incorrect peer dependency "react@>=16.8".
warning " > react-router-dom@6.0.0-beta.0" has incorrect peer dependency "react-dom@>=16.8".
warning " > react-switch@5.0.1" has incorrect peer dependency "react@^15.3.0 || ^16.0.0".
warning " > react-switch@5.0.1" has incorrect peer dependency "react-dom@^15.3.0 || ^16.0.0".
warning " > react-table@7.6.2" has incorrect peer dependency "react@^16.8.3 || ^17.0.0-0".
warning " > react-tabs@3.1.1" has incorrect peer dependency "react@^16.3.0".
warning " > react-tiny-fab@3.5.0" has incorrect peer dependency "react@>= 16.8".
warning " > react-tiny-fab@3.5.0" has incorrect peer dependency "react-dom@>= 16.8".
warning " > react-window@1.8.6" has incorrect peer dependency "react@^15.0.0 || ^16.0.0 || ^17.0.0".
warning " > react-window@1.8.6" has incorrect peer dependency "react-dom@^15.0.0 || ^16.0.0 || ^17.0.0".
warning " > recoil@0.1.2" has incorrect peer dependency "react@^16.13.1".
warning " > fork-ts-checker-notifier-webpack-plugin@3.0.0" has incorrect peer dependency "fork-ts-checker-webpack-plugin@^5.0.0".
warning " > workbox-webpack-plugin@5.1.4" has incorrect peer dependency "webpack@^4.0.0".
[4/4] Building fresh packages...
Done in 99.25s.
yarn run v1.22.5
$ NODE_ENV=production webpack
(node:97) [DEP_WEBPACK_SINGLE_ENTRY_PLUGIN] DeprecationWarning: SingleEntryPlugin was renamed to EntryPlugin
(Use `node --trace-deprecation ...` to show where the warning was created)
/app/node_modules/source-map/lib/util.js:24
    throw new Error('"' + aName + '" is a required argument.');
          ^

Error: "version" is a required argument.
    at Object.getArg (/app/node_modules/source-map/lib/util.js:24:11)
    at new BasicSourceMapConsumer (/app/node_modules/source-map/lib/source-map-consumer.js:294:22)
    at new SourceMapConsumer (/app/node_modules/source-map/lib/source-map-consumer.js:22:7)
    at SourceMapSource.node (/app/node_modules/webpack/node_modules/webpack-sources/lib/SourceMapSource.js:193:4)
    at exports.getSourceAndMap (/app/node_modules/webpack/node_modules/webpack-sources/lib/helpers.js:20:27)
    at SourceMapSource.sourceAndMap (/app/node_modules/webpack/node_modules/webpack-sources/lib/SourceMapSource.js:184:10)
    at getTaskForFile (/app/node_modules/webpack/lib/SourceMapDevToolPlugin.js:78:30)
    at /app/node_modules/webpack/lib/SourceMapDevToolPlugin.js:265:22
    at /app/node_modules/webpack/lib/Cache.js:85:6
    at /app/node_modules/webpack/lib/Cache.js:39:11
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: Service 'yacd' failed to build : The command '/bin/sh -c yarn config set network-timeout 300000   && yarn   && yarn build   && rm public/*.map' returned a non-zero code: 1
```

**Comment by haishanh** [comment]
[Google 了一下](https://www.google.com/search?q=source-map+version+is+a+required+argument&oq=source-map+version+is+a+required+argument&aqs=chrome..69i57.14797j0j4&sourceid=chrome&ie=UTF-8)，并不清楚这是什么奇葩问题，也不打算深挖。

看着像是依赖版本的问题，你可以尝试 check `dev` branch，我刚刚更新了一些依赖。

另外，如果不是自己要改什么东西的话，实在没有任何理由自己重新 build。现在 Docker hub 上的 image 也都是通过 GitHub action 自动 build 和 push 的。

**Comment by hootigger** [comment]
谢谢回复，而且我在mac 以及unRaid（NAS）均可以正常编译，放在服务器时候发生错误。搜索无果。
我刚才又试试dev，还是一样的问题。就很奇怪。
不过确实也没必要自己重新编译。后面我也打算直接用你弄好的镜像了。
