### ISSUE TITLE
连接功能无法使用，提示 Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by rebron1900** [haishanh/yacd#724]
```
Connections.07c28cc0.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at di (Connections.07c28cc0.js:1:68259)
    at pi (Connections.07c28cc0.js:1:69001)
    at Connections.07c28cc0.js:1:69509
    at Array.map (<anonymous>)
    at Connections.07c28cc0.js:1:69501
    at index.5faed7a7.js:101:9304
    at Array.forEach (<anonymous>)
    at KD (index.5faed7a7.js:101:9293)
    at WebSocket.<anonymous> (index.5faed7a7.js:101:9473)
```

**Comment by haishanh** [comment]
要升级一下 clash，yacd 这边没做好兼容

**Comment by rebron1900** [comment]
感谢答复，用的shellclash，估计没辙了~

**Comment by peanut996** [comment]
同遇到这个问题 使用版本为clash 1.5.1

**Comment by peanut996** [comment]
#727  已提交PR

**Comment by rebron1900** [comment]
动手能力强就是好啊

**Comment by peanut996** [comment]
> 动手能力强就是好啊

作者已经修好了

**Comment by fxzxmicah** [comment]
为什么要死守老版本呢？

**Comment by peanut996** [comment]
> 为什么要死守老版本呢？

有些人的clash 是在嵌入式设备的，可能常年不更新。

**Comment by rebron1900** [comment]
我是在路由器上用的shellclash
